version = '2'

[linters]
default = 'all'
disable = [ 'gomodguard', 'wsl' ]

[[linters.exclusions.rules]]
path = 'internal/gen/random.go'
linters = [ 'gochecknoglobals' ]

[[linters.exclusions.rules]]
path = 'internal/test/line.go'
linters = [ 'prealloc' ]

[linters.settings.depguard.rules.main]
allow = [
  '$gostd',
  'github.com/dgf/tygo/internal',
  'golang.org/x/term'
]

[linters.settings.goconst]
ignore-string-values = [ 'bar', 'foo', 'one', 'two' ]

[linters.settings.gosec]
excludes = [ 'G404' ]

[linters.settings.mnd]
ignored-files = [ 'internal/config/default.go' ]
ignored-functions = [ 'os.Mkdir', 'os.WriteFile' ]
ignored-numbers = [ '2', '100' ]

[[linters.settings.revive.rules]]
name = 'exported'
arguments = [
  'disable-checks-on-constants',
  'disable-checks-on-functions',
  'disable-checks-on-methods',
  'disable-checks-on-types',
  'disable-checks-on-variables'
]

[linters.settings.varnamelen]
max-distance = 17
min-name-length = 3
check-receiver = false
ignore-decls = [
  'r rune'
]

